# https://cloud.google.com/appengine/docs/python/config/appref
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /http://tr[0-5]\.torrent4me\.com/ann(ounce\.php|)
  script: announce.app

- url: /.*
  script: sim-sim.app
  secure: always

libraries:
- name: webapp2
  version: latest
  
